#############################################################################
# Makefile for building: ChatClient
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Oct 11 09:30:17 2024
# Project:  ChatClient.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ChatClient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		view/chatwidget.cpp \
		view/loginwidget.cpp \
		thread/readthread.cpp \
		thread/writethread.cpp \
		network/socketconnect.cpp moc_chatwidget.cpp \
		moc_loginwidget.cpp \
		moc_readthread.cpp \
		moc_writethread.cpp
OBJECTS       = main.o \
		chatwidget.o \
		loginwidget.o \
		readthread.o \
		writethread.o \
		socketconnect.o \
		moc_chatwidget.o \
		moc_loginwidget.o \
		moc_readthread.o \
		moc_writethread.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ChatClient.pro
QMAKE_TARGET  = ChatClient
DESTDIR       = 
TARGET        = ChatClient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_loginwidget.h ui_chatwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ChatClient.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ChatClient.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ChatClient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ChatClient1.0.0 || $(MKDIR) .tmp/ChatClient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ChatClient1.0.0/ && $(COPY_FILE) --parents view/chatwidget.h view/loginwidget.h agreement/protocol.h thread/readthread.h thread/writethread.h network/socketconnect.h .tmp/ChatClient1.0.0/ && $(COPY_FILE) --parents main.cpp view/chatwidget.cpp view/loginwidget.cpp thread/readthread.cpp thread/writethread.cpp network/socketconnect.cpp .tmp/ChatClient1.0.0/ && $(COPY_FILE) --parents loginwidget.ui chatwidget.ui .tmp/ChatClient1.0.0/ && (cd `dirname .tmp/ChatClient1.0.0` && $(TAR) ChatClient1.0.0.tar ChatClient1.0.0 && $(COMPRESS) ChatClient1.0.0.tar) && $(MOVE) `dirname .tmp/ChatClient1.0.0`/ChatClient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ChatClient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_chatwidget.cpp moc_loginwidget.cpp moc_readthread.cpp moc_writethread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chatwidget.cpp moc_loginwidget.cpp moc_readthread.cpp moc_writethread.cpp
moc_chatwidget.cpp: view/chatwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) view/chatwidget.h -o moc_chatwidget.cpp

moc_loginwidget.cpp: view/chatwidget.h \
		view/loginwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) view/loginwidget.h -o moc_loginwidget.cpp

moc_readthread.cpp: agreement/protocol.h \
		thread/readthread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) thread/readthread.h -o moc_readthread.cpp

moc_writethread.cpp: agreement/protocol.h \
		thread/writethread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) thread/writethread.h -o moc_writethread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginwidget.h ui_chatwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginwidget.h ui_chatwidget.h
ui_loginwidget.h: loginwidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic loginwidget.ui -o ui_loginwidget.h

ui_chatwidget.h: chatwidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic chatwidget.ui -o ui_chatwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp view/loginwidget.h \
		view/chatwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

chatwidget.o: view/chatwidget.cpp view/chatwidget.h \
		ui_chatwidget.h \
		agreement/protocol.h \
		thread/readthread.h \
		thread/writethread.h \
		network/socketconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatwidget.o view/chatwidget.cpp

loginwidget.o: view/loginwidget.cpp view/loginwidget.h \
		view/chatwidget.h \
		ui_loginwidget.h \
		agreement/protocol.h \
		network/socketconnect.h \
		thread/readthread.h \
		thread/writethread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwidget.o view/loginwidget.cpp

readthread.o: thread/readthread.cpp thread/readthread.h \
		agreement/protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readthread.o thread/readthread.cpp

writethread.o: thread/writethread.cpp thread/writethread.h \
		agreement/protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writethread.o thread/writethread.cpp

socketconnect.o: network/socketconnect.cpp network/socketconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketconnect.o network/socketconnect.cpp

moc_chatwidget.o: moc_chatwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatwidget.o moc_chatwidget.cpp

moc_loginwidget.o: moc_loginwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwidget.o moc_loginwidget.cpp

moc_readthread.o: moc_readthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readthread.o moc_readthread.cpp

moc_writethread.o: moc_writethread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_writethread.o moc_writethread.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ChatClient/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/ChatClient/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/ChatClient/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/ChatClient/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ChatClient/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

